# Generated by Django 4.2.6 on 2023-10-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
